#! /bin/sh
# /etc/init.d/djmount
#
# /usr/sbin/djmount
### BEGIN INIT INFO
# Provides:          djmount
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: upnp daemon
# Description:       DJMOUNT
### END INIT INFO
case "$1" in
    start)
        echo -n "Starting Djmount "
        djmount -o allow_other,nonempty,iocharset=utf-8 /mnt/UPNP
        ;;
    stop)
        echo -n "Shutting Djmount "
        ## Stop daemon with killproc(8) and if this fails
        ## killproc sets the return value according to LSB.

        killall djmount
                umount /mnt/UPNP
        ;;
esac
