#! /bin/sh
# /etc/init.d/mtrack
#
### BEGIN INIT INFO
# Provides: mtrack
#Required-Start: $all 
#Required-Stop: $mpd 
#Default-Start: 2 3 4 5 
#Default-Stop: 0 1 6 
#Short-Description: M-Track 
#Description: Mtrack 
### END INIT INFO
# Some things that run always
case "$1" in
  start) 

/bin/bash /var/www/command/mtrack.sh
;;
  stop)
    ;;
  *)
    echo "Usage: /etc/init.d/myruns {start|stop}"
    exit 1
    ;;
esac
exit 0
