#! /bin/sh
# /etc/init.d/shairport
#
### BEGIN INIT INFO
# Provides:          shairport
# Required-Start:    alsa-utils hostname avahi
# Required-Stop:     alsa-utils hostname avahi
# Short-Description: shairport - Airtunes emulator!
# Description:       Airtunes emulator!
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO
NAME="Volumio"
 
case "$1" in
  start)
    /usr/local/bin/shairport -d -a "$NAME" -B "mpc stop"
    ;;
  stop)
    killall shairport
    ;;
  *)
    echo "Usage: /etc/init.d/shairport {start|stop}"
    exit 1
    ;;
esac
 
exit 0
